language: python

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools tox virtualenv
  - pip install coverage coveralls
  - pip install numpy>=1.6.1
  - pip install pandas>=0.20.1

script:
  - tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django14
    - python: 2.7
      env: TOXENV=py27-django15_nosouth
    - python: 2.7
      env: TOXENV=py27-django15
    - python: 2.7
      env: TOXENV=py27-django16
    - python: 2.7
      env: TOXENV=py27-django17
    - python: 2.7
      env: TOXENV=py27-django18
    - python: 2.7
      env: TOXENV=py27-django19
    - python: 2.7
      env: TOXENV=py27-django10
    - python: 2.7
      env: TOXENV=py27-django11 
    - python: 3.4
      env: TOXENV=py34-django17 
    - python: 3.4
      env: TOXENV=py34-django18
    - python: 3.4
      env: TOXENV=py34-django19
    - python: 3.4
      env: TOXENV=py34-django10
    - python: 3.4
      env: TOXENV=py34-django11
    - python: 3.5
      env: TOXENV=py35-django18
    - python: 3.5
      env: TOXENV=py35-django19
    - python: 3.5
      env: TOXENV=py35-django10
    - python: 3.5
      env: TOXENV=py35-django11
    - python: 3.6
      env: TOXENV=py36-django11


after_success: coveralls
